<script src="<?php echo e(asset('fashi/js/jquery-3.3.1.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/bootstrap.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery-ui.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery.countdown.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery.nice-select.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery.zoom.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery.dd.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/jquery.slicknav.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/owl.carousel.min.js')); ?>"></script>
<script src="<?php echo e(asset('fashi/js/main.js')); ?>"></script>
<!-- Custom Script File -->
<script src="<?php echo e(asset('assets/script.js')); ?>"></script>
<?php /**PATH C:\Users\bouad\Documents\GitHub\shopmetics\resources\views/includes/js.blade.php ENDPATH**/ ?>