<link rel="stylesheet" href="{{ asset('fashi/css/bootstrap.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/font-awesome.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/themify-icons.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/elegant-icons.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/owl.carousel.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/nice-select.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/jquery-ui.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/slicknav.min.css') }}" type="text/css">
<link rel="stylesheet" href="{{ asset('fashi/css/style.css') }}" type="text/css">
